//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiiconWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wstienda.autofinanciera.com.co/", ConfigurationName="SiiconWebService.WSTiendaSoap")]
    public interface WSTiendaSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wstienda.autofinanciera.com.co/ConsultarFacturaReferencia", ReplyAction="*")]
        System.Threading.Tasks.Task<global::SiiconWebService.ConsultarFacturaReferenciaResponse> ConsultarFacturaReferenciaAsync(global::SiiconWebService.ConsultarFacturaReferenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wstienda.autofinanciera.com.co/ConsultarFacturasCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<global::SiiconWebService.ConsultarFacturasClienteResponse> ConsultarFacturasClienteAsync(global::SiiconWebService.ConsultarFacturasClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wstienda.autofinanciera.com.co/SelecccionarCompañias", ReplyAction="*")]
        System.Threading.Tasks.Task<global::SiiconWebService.SelecccionarCompañiasResponse> SelecccionarCompañiasAsync(global::SiiconWebService.SelecccionarCompañiasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wstienda.autofinanciera.com.co/SelecccionarAgencias", ReplyAction="*")]
        System.Threading.Tasks.Task<global::SiiconWebService.SelecccionarAgenciasResponse> SelecccionarAgenciasAsync(global::SiiconWebService.SelecccionarAgenciasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wstienda.autofinanciera.com.co/SelecccionarMarcas", ReplyAction="*")]
        System.Threading.Tasks.Task<global::SiiconWebService.SelecccionarMarcasResponse> SelecccionarMarcasAsync(global::SiiconWebService.SelecccionarMarcasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wstienda.autofinanciera.com.co/SelecccionarPorcAdministracionCompañia", ReplyAction="*")]
        System.Threading.Tasks.Task<global::SiiconWebService.SelecccionarPorcAdministracionCompañiaResponse> SelecccionarPorcAdministracionCompañiaAsync(global::SiiconWebService.SelecccionarPorcAdministracionCompañiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wstienda.autofinanciera.com.co/SelecccionarPorcInscripcionCompañia", ReplyAction="*")]
        System.Threading.Tasks.Task<global::SiiconWebService.SelecccionarPorcInscripcionCompañiaResponse> SelecccionarPorcInscripcionCompañiaAsync(global::SiiconWebService.SelecccionarPorcInscripcionCompañiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wstienda.autofinanciera.com.co/SelecccionarTiposBienesCompañia", ReplyAction="*")]
        System.Threading.Tasks.Task<global::SiiconWebService.SelecccionarTiposBienesCompañiaResponse> SelecccionarTiposBienesCompañiaAsync(global::SiiconWebService.SelecccionarTiposBienesCompañiaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarFacturaReferenciaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarFacturaReferencia", Namespace="http://wstienda.autofinanciera.com.co/", Order=0)]
        public global::SiiconWebService.ConsultarFacturaReferenciaRequestBody Body;
        
        public ConsultarFacturaReferenciaRequest()
        {
        }
        
        public ConsultarFacturaReferenciaRequest(global::SiiconWebService.ConsultarFacturaReferenciaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wstienda.autofinanciera.com.co/")]
    public partial class ConsultarFacturaReferenciaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string referenciaFactura;
        
        public ConsultarFacturaReferenciaRequestBody()
        {
        }
        
        public ConsultarFacturaReferenciaRequestBody(string referenciaFactura)
        {
            this.referenciaFactura = referenciaFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarFacturaReferenciaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarFacturaReferenciaResponse", Namespace="http://wstienda.autofinanciera.com.co/", Order=0)]
        public global::SiiconWebService.ConsultarFacturaReferenciaResponseBody Body;
        
        public ConsultarFacturaReferenciaResponse()
        {
        }
        
        public ConsultarFacturaReferenciaResponse(global::SiiconWebService.ConsultarFacturaReferenciaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wstienda.autofinanciera.com.co/")]
    public partial class ConsultarFacturaReferenciaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarFacturaReferenciaResult;
        
        public ConsultarFacturaReferenciaResponseBody()
        {
        }
        
        public ConsultarFacturaReferenciaResponseBody(string ConsultarFacturaReferenciaResult)
        {
            this.ConsultarFacturaReferenciaResult = ConsultarFacturaReferenciaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarFacturasClienteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarFacturasCliente", Namespace="http://wstienda.autofinanciera.com.co/", Order=0)]
        public global::SiiconWebService.ConsultarFacturasClienteRequestBody Body;
        
        public ConsultarFacturasClienteRequest()
        {
        }
        
        public ConsultarFacturasClienteRequest(global::SiiconWebService.ConsultarFacturasClienteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wstienda.autofinanciera.com.co/")]
    public partial class ConsultarFacturasClienteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IdentificacionCliente;
        
        public ConsultarFacturasClienteRequestBody()
        {
        }
        
        public ConsultarFacturasClienteRequestBody(string IdentificacionCliente)
        {
            this.IdentificacionCliente = IdentificacionCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarFacturasClienteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarFacturasClienteResponse", Namespace="http://wstienda.autofinanciera.com.co/", Order=0)]
        public global::SiiconWebService.ConsultarFacturasClienteResponseBody Body;
        
        public ConsultarFacturasClienteResponse()
        {
        }
        
        public ConsultarFacturasClienteResponse(global::SiiconWebService.ConsultarFacturasClienteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wstienda.autofinanciera.com.co/")]
    public partial class ConsultarFacturasClienteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarFacturasClienteResult;
        
        public ConsultarFacturasClienteResponseBody()
        {
        }
        
        public ConsultarFacturasClienteResponseBody(string ConsultarFacturasClienteResult)
        {
            this.ConsultarFacturasClienteResult = ConsultarFacturasClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelecccionarCompañiasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelecccionarCompañias", Namespace="http://wstienda.autofinanciera.com.co/", Order=0)]
        public global::SiiconWebService.SelecccionarCompañiasRequestBody Body;
        
        public SelecccionarCompañiasRequest()
        {
        }
        
        public SelecccionarCompañiasRequest(global::SiiconWebService.SelecccionarCompañiasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelecccionarCompañiasRequestBody
    {
        
        public SelecccionarCompañiasRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelecccionarCompañiasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelecccionarCompañiasResponse", Namespace="http://wstienda.autofinanciera.com.co/", Order=0)]
        public global::SiiconWebService.SelecccionarCompañiasResponseBody Body;
        
        public SelecccionarCompañiasResponse()
        {
        }
        
        public SelecccionarCompañiasResponse(global::SiiconWebService.SelecccionarCompañiasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wstienda.autofinanciera.com.co/")]
    public partial class SelecccionarCompañiasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelecccionarCompañiasResult;
        
        public SelecccionarCompañiasResponseBody()
        {
        }
        
        public SelecccionarCompañiasResponseBody(string SelecccionarCompañiasResult)
        {
            this.SelecccionarCompañiasResult = SelecccionarCompañiasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelecccionarAgenciasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelecccionarAgencias", Namespace="http://wstienda.autofinanciera.com.co/", Order=0)]
        public global::SiiconWebService.SelecccionarAgenciasRequestBody Body;
        
        public SelecccionarAgenciasRequest()
        {
        }
        
        public SelecccionarAgenciasRequest(global::SiiconWebService.SelecccionarAgenciasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelecccionarAgenciasRequestBody
    {
        
        public SelecccionarAgenciasRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelecccionarAgenciasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelecccionarAgenciasResponse", Namespace="http://wstienda.autofinanciera.com.co/", Order=0)]
        public global::SiiconWebService.SelecccionarAgenciasResponseBody Body;
        
        public SelecccionarAgenciasResponse()
        {
        }
        
        public SelecccionarAgenciasResponse(global::SiiconWebService.SelecccionarAgenciasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wstienda.autofinanciera.com.co/")]
    public partial class SelecccionarAgenciasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelecccionarAgenciasResult;
        
        public SelecccionarAgenciasResponseBody()
        {
        }
        
        public SelecccionarAgenciasResponseBody(string SelecccionarAgenciasResult)
        {
            this.SelecccionarAgenciasResult = SelecccionarAgenciasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelecccionarMarcasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelecccionarMarcas", Namespace="http://wstienda.autofinanciera.com.co/", Order=0)]
        public global::SiiconWebService.SelecccionarMarcasRequestBody Body;
        
        public SelecccionarMarcasRequest()
        {
        }
        
        public SelecccionarMarcasRequest(global::SiiconWebService.SelecccionarMarcasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelecccionarMarcasRequestBody
    {
        
        public SelecccionarMarcasRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelecccionarMarcasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelecccionarMarcasResponse", Namespace="http://wstienda.autofinanciera.com.co/", Order=0)]
        public global::SiiconWebService.SelecccionarMarcasResponseBody Body;
        
        public SelecccionarMarcasResponse()
        {
        }
        
        public SelecccionarMarcasResponse(global::SiiconWebService.SelecccionarMarcasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wstienda.autofinanciera.com.co/")]
    public partial class SelecccionarMarcasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelecccionarMarcasResult;
        
        public SelecccionarMarcasResponseBody()
        {
        }
        
        public SelecccionarMarcasResponseBody(string SelecccionarMarcasResult)
        {
            this.SelecccionarMarcasResult = SelecccionarMarcasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelecccionarPorcAdministracionCompañiaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelecccionarPorcAdministracionCompañia", Namespace="http://wstienda.autofinanciera.com.co/", Order=0)]
        public global::SiiconWebService.SelecccionarPorcAdministracionCompañiaRequestBody Body;
        
        public SelecccionarPorcAdministracionCompañiaRequest()
        {
        }
        
        public SelecccionarPorcAdministracionCompañiaRequest(global::SiiconWebService.SelecccionarPorcAdministracionCompañiaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wstienda.autofinanciera.com.co/")]
    public partial class SelecccionarPorcAdministracionCompañiaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CompañiaId;
        
        public SelecccionarPorcAdministracionCompañiaRequestBody()
        {
        }
        
        public SelecccionarPorcAdministracionCompañiaRequestBody(string CompañiaId)
        {
            this.CompañiaId = CompañiaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelecccionarPorcAdministracionCompañiaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelecccionarPorcAdministracionCompañiaResponse", Namespace="http://wstienda.autofinanciera.com.co/", Order=0)]
        public global::SiiconWebService.SelecccionarPorcAdministracionCompañiaResponseBody Body;
        
        public SelecccionarPorcAdministracionCompañiaResponse()
        {
        }
        
        public SelecccionarPorcAdministracionCompañiaResponse(global::SiiconWebService.SelecccionarPorcAdministracionCompañiaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wstienda.autofinanciera.com.co/")]
    public partial class SelecccionarPorcAdministracionCompañiaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelecccionarPorcAdministracionCompañiaResult;
        
        public SelecccionarPorcAdministracionCompañiaResponseBody()
        {
        }
        
        public SelecccionarPorcAdministracionCompañiaResponseBody(string SelecccionarPorcAdministracionCompañiaResult)
        {
            this.SelecccionarPorcAdministracionCompañiaResult = SelecccionarPorcAdministracionCompañiaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelecccionarPorcInscripcionCompañiaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelecccionarPorcInscripcionCompañia", Namespace="http://wstienda.autofinanciera.com.co/", Order=0)]
        public global::SiiconWebService.SelecccionarPorcInscripcionCompañiaRequestBody Body;
        
        public SelecccionarPorcInscripcionCompañiaRequest()
        {
        }
        
        public SelecccionarPorcInscripcionCompañiaRequest(global::SiiconWebService.SelecccionarPorcInscripcionCompañiaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wstienda.autofinanciera.com.co/")]
    public partial class SelecccionarPorcInscripcionCompañiaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CompañiaId;
        
        public SelecccionarPorcInscripcionCompañiaRequestBody()
        {
        }
        
        public SelecccionarPorcInscripcionCompañiaRequestBody(string CompañiaId)
        {
            this.CompañiaId = CompañiaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelecccionarPorcInscripcionCompañiaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelecccionarPorcInscripcionCompañiaResponse", Namespace="http://wstienda.autofinanciera.com.co/", Order=0)]
        public global::SiiconWebService.SelecccionarPorcInscripcionCompañiaResponseBody Body;
        
        public SelecccionarPorcInscripcionCompañiaResponse()
        {
        }
        
        public SelecccionarPorcInscripcionCompañiaResponse(global::SiiconWebService.SelecccionarPorcInscripcionCompañiaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wstienda.autofinanciera.com.co/")]
    public partial class SelecccionarPorcInscripcionCompañiaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelecccionarPorcInscripcionCompañiaResult;
        
        public SelecccionarPorcInscripcionCompañiaResponseBody()
        {
        }
        
        public SelecccionarPorcInscripcionCompañiaResponseBody(string SelecccionarPorcInscripcionCompañiaResult)
        {
            this.SelecccionarPorcInscripcionCompañiaResult = SelecccionarPorcInscripcionCompañiaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelecccionarTiposBienesCompañiaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelecccionarTiposBienesCompañia", Namespace="http://wstienda.autofinanciera.com.co/", Order=0)]
        public global::SiiconWebService.SelecccionarTiposBienesCompañiaRequestBody Body;
        
        public SelecccionarTiposBienesCompañiaRequest()
        {
        }
        
        public SelecccionarTiposBienesCompañiaRequest(global::SiiconWebService.SelecccionarTiposBienesCompañiaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wstienda.autofinanciera.com.co/")]
    public partial class SelecccionarTiposBienesCompañiaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CompañiaId;
        
        public SelecccionarTiposBienesCompañiaRequestBody()
        {
        }
        
        public SelecccionarTiposBienesCompañiaRequestBody(string CompañiaId)
        {
            this.CompañiaId = CompañiaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelecccionarTiposBienesCompañiaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelecccionarTiposBienesCompañiaResponse", Namespace="http://wstienda.autofinanciera.com.co/", Order=0)]
        public global::SiiconWebService.SelecccionarTiposBienesCompañiaResponseBody Body;
        
        public SelecccionarTiposBienesCompañiaResponse()
        {
        }
        
        public SelecccionarTiposBienesCompañiaResponse(global::SiiconWebService.SelecccionarTiposBienesCompañiaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wstienda.autofinanciera.com.co/")]
    public partial class SelecccionarTiposBienesCompañiaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelecccionarTiposBienesCompañiaResult;
        
        public SelecccionarTiposBienesCompañiaResponseBody()
        {
        }
        
        public SelecccionarTiposBienesCompañiaResponseBody(string SelecccionarTiposBienesCompañiaResult)
        {
            this.SelecccionarTiposBienesCompañiaResult = SelecccionarTiposBienesCompañiaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface WSTiendaSoapChannel : global::SiiconWebService.WSTiendaSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class WSTiendaSoapClient : System.ServiceModel.ClientBase<global::SiiconWebService.WSTiendaSoap>, global::SiiconWebService.WSTiendaSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSTiendaSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WSTiendaSoapClient.GetBindingForEndpoint(endpointConfiguration), WSTiendaSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSTiendaSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSTiendaSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSTiendaSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSTiendaSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSTiendaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::SiiconWebService.ConsultarFacturaReferenciaResponse> global::SiiconWebService.WSTiendaSoap.ConsultarFacturaReferenciaAsync(global::SiiconWebService.ConsultarFacturaReferenciaRequest request)
        {
            return base.Channel.ConsultarFacturaReferenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::SiiconWebService.ConsultarFacturaReferenciaResponse> ConsultarFacturaReferenciaAsync(string referenciaFactura)
        {
            global::SiiconWebService.ConsultarFacturaReferenciaRequest inValue = new global::SiiconWebService.ConsultarFacturaReferenciaRequest();
            inValue.Body = new global::SiiconWebService.ConsultarFacturaReferenciaRequestBody();
            inValue.Body.referenciaFactura = referenciaFactura;
            return ((global::SiiconWebService.WSTiendaSoap)(this)).ConsultarFacturaReferenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::SiiconWebService.ConsultarFacturasClienteResponse> global::SiiconWebService.WSTiendaSoap.ConsultarFacturasClienteAsync(global::SiiconWebService.ConsultarFacturasClienteRequest request)
        {
            return base.Channel.ConsultarFacturasClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::SiiconWebService.ConsultarFacturasClienteResponse> ConsultarFacturasClienteAsync(string IdentificacionCliente)
        {
            global::SiiconWebService.ConsultarFacturasClienteRequest inValue = new global::SiiconWebService.ConsultarFacturasClienteRequest();
            inValue.Body = new global::SiiconWebService.ConsultarFacturasClienteRequestBody();
            inValue.Body.IdentificacionCliente = IdentificacionCliente;
            return ((global::SiiconWebService.WSTiendaSoap)(this)).ConsultarFacturasClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::SiiconWebService.SelecccionarCompañiasResponse> global::SiiconWebService.WSTiendaSoap.SelecccionarCompañiasAsync(global::SiiconWebService.SelecccionarCompañiasRequest request)
        {
            return base.Channel.SelecccionarCompañiasAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::SiiconWebService.SelecccionarCompañiasResponse> SelecccionarCompañiasAsync()
        {
            global::SiiconWebService.SelecccionarCompañiasRequest inValue = new global::SiiconWebService.SelecccionarCompañiasRequest();
            inValue.Body = new global::SiiconWebService.SelecccionarCompañiasRequestBody();
            return ((global::SiiconWebService.WSTiendaSoap)(this)).SelecccionarCompañiasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::SiiconWebService.SelecccionarAgenciasResponse> global::SiiconWebService.WSTiendaSoap.SelecccionarAgenciasAsync(global::SiiconWebService.SelecccionarAgenciasRequest request)
        {
            return base.Channel.SelecccionarAgenciasAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::SiiconWebService.SelecccionarAgenciasResponse> SelecccionarAgenciasAsync()
        {
            global::SiiconWebService.SelecccionarAgenciasRequest inValue = new global::SiiconWebService.SelecccionarAgenciasRequest();
            inValue.Body = new global::SiiconWebService.SelecccionarAgenciasRequestBody();
            return ((global::SiiconWebService.WSTiendaSoap)(this)).SelecccionarAgenciasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::SiiconWebService.SelecccionarMarcasResponse> global::SiiconWebService.WSTiendaSoap.SelecccionarMarcasAsync(global::SiiconWebService.SelecccionarMarcasRequest request)
        {
            return base.Channel.SelecccionarMarcasAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::SiiconWebService.SelecccionarMarcasResponse> SelecccionarMarcasAsync()
        {
            global::SiiconWebService.SelecccionarMarcasRequest inValue = new global::SiiconWebService.SelecccionarMarcasRequest();
            inValue.Body = new global::SiiconWebService.SelecccionarMarcasRequestBody();
            return ((global::SiiconWebService.WSTiendaSoap)(this)).SelecccionarMarcasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::SiiconWebService.SelecccionarPorcAdministracionCompañiaResponse> global::SiiconWebService.WSTiendaSoap.SelecccionarPorcAdministracionCompañiaAsync(global::SiiconWebService.SelecccionarPorcAdministracionCompañiaRequest request)
        {
            return base.Channel.SelecccionarPorcAdministracionCompañiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::SiiconWebService.SelecccionarPorcAdministracionCompañiaResponse> SelecccionarPorcAdministracionCompañiaAsync(string CompañiaId)
        {
            global::SiiconWebService.SelecccionarPorcAdministracionCompañiaRequest inValue = new global::SiiconWebService.SelecccionarPorcAdministracionCompañiaRequest();
            inValue.Body = new global::SiiconWebService.SelecccionarPorcAdministracionCompañiaRequestBody();
            inValue.Body.CompañiaId = CompañiaId;
            return ((global::SiiconWebService.WSTiendaSoap)(this)).SelecccionarPorcAdministracionCompañiaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::SiiconWebService.SelecccionarPorcInscripcionCompañiaResponse> global::SiiconWebService.WSTiendaSoap.SelecccionarPorcInscripcionCompañiaAsync(global::SiiconWebService.SelecccionarPorcInscripcionCompañiaRequest request)
        {
            return base.Channel.SelecccionarPorcInscripcionCompañiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::SiiconWebService.SelecccionarPorcInscripcionCompañiaResponse> SelecccionarPorcInscripcionCompañiaAsync(string CompañiaId)
        {
            global::SiiconWebService.SelecccionarPorcInscripcionCompañiaRequest inValue = new global::SiiconWebService.SelecccionarPorcInscripcionCompañiaRequest();
            inValue.Body = new global::SiiconWebService.SelecccionarPorcInscripcionCompañiaRequestBody();
            inValue.Body.CompañiaId = CompañiaId;
            return ((global::SiiconWebService.WSTiendaSoap)(this)).SelecccionarPorcInscripcionCompañiaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::SiiconWebService.SelecccionarTiposBienesCompañiaResponse> global::SiiconWebService.WSTiendaSoap.SelecccionarTiposBienesCompañiaAsync(global::SiiconWebService.SelecccionarTiposBienesCompañiaRequest request)
        {
            return base.Channel.SelecccionarTiposBienesCompañiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::SiiconWebService.SelecccionarTiposBienesCompañiaResponse> SelecccionarTiposBienesCompañiaAsync(string CompañiaId)
        {
            global::SiiconWebService.SelecccionarTiposBienesCompañiaRequest inValue = new global::SiiconWebService.SelecccionarTiposBienesCompañiaRequest();
            inValue.Body = new global::SiiconWebService.SelecccionarTiposBienesCompañiaRequestBody();
            inValue.Body.CompañiaId = CompañiaId;
            return ((global::SiiconWebService.WSTiendaSoap)(this)).SelecccionarTiposBienesCompañiaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSTiendaSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSTiendaSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSTiendaSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://wstienda.autofinanciera.com.co/wstienda.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSTiendaSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://wstienda.autofinanciera.com.co/wstienda.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSTiendaSoap,
            
            WSTiendaSoap12,
        }
    }
}
